<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Renci.SshNet</AssemblyName>
    <Product>SSH.NET</Product>
    <AssemblyTitle>SSH.NET</AssemblyTitle>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SSH.NET</PackageId>
    <Title>SSH.NET</Title>
    <Description>SSH.NET is a Secure Shell (SSH) library for .NET, optimized for parallelism.</Description>
    <Copyright>Copyright © Renci 2010-$([System.DateTime]::UtcNow.Year)</Copyright>
    <Authors>Renci</Authors>
    <PackageTags>ssh; scp; sftp</PackageTags>
    <PackageReleaseNotes>https://github.com/sshnet/SSH.NET/releases/tag/$(Version)</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>

</Project>
